name: "Test"

on:
  push:
    branches: ["main"]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@v4
      - run: echo "make pull of code"
      - run: echo "run migrations"
      - run: echo "Publish version"
